import type { Person } from "./people-types";
import { PEOPLE as CURATED } from "./people";

// Best-effort: import Codex-generated by-type files if present.
// Each is optional — we no-op if a type's file hasn't been generated yet.
import { PEOPLE_SCIENTIST } from "./by-type/scientist";
import { PEOPLE_ENGINEER }  from "./by-type/engineer";
import { PEOPLE_MERCHANT }  from "./by-type/merchant";
import { PEOPLE_WRITER }    from "./by-type/writer";
import { PEOPLE_ARTIST }    from "./by-type/artist";
import { PEOPLE_MUSICIAN }  from "./by-type/musician";
import { PEOPLE_GENERAL }   from "./by-type/general";
import { PEOPLE_ADMIRAL }   from "./by-type/admiral";
import { PEOPLE_PROPHET }   from "./by-type/prophet";

// Normalize a name down to {first-word, last-word} so e.g.
//   "Wolfgang Amadeus Mozart" ~ "Wolfgang Mozart"
//   "Vincent van Gogh"        ~ "Vincent Van Gogh"
function nameKey(name: string): string {
  const tokens = name
    .toLowerCase()
    .replace(/[.,]/g, "")
    .split(/\s+/)
    .filter((w) => !["van", "von", "de", "del", "della", "di", "da", "ibn", "al", "el", "the", "of", "the"].includes(w));
  if (tokens.length <= 1) return tokens.join("");
  return tokens[0] + ":" + tokens[tokens.length - 1];
}

function dedupe(list: Person[]): Person[] {
  const seen = new Map<string, Person>();
  for (const p of list) {
    // Dedupe by NAME alone (not type) so e.g. Zheng He doesn't appear as both
    // Admiral and Merchant. First entry wins — the import order in this file
    // sets the priority.
    const key = nameKey(p.name);
    if (!seen.has(key)) seen.set(key, p);
  }
  return [...seen.values()].sort((a, b) => (a.born ?? 0) - (b.born ?? 0));
}

export const ALL_PEOPLE: Person[] = dedupe([
  ...CURATED,
  ...PEOPLE_SCIENTIST,
  ...PEOPLE_ENGINEER,
  ...PEOPLE_MERCHANT,
  ...PEOPLE_WRITER,
  ...PEOPLE_ARTIST,
  ...PEOPLE_MUSICIAN,
  ...PEOPLE_GENERAL,
  ...PEOPLE_ADMIRAL,
  ...PEOPLE_PROPHET,
]);
