import type { Person } from "./people-types";
import { PEOPLE as CURATED } from "./people";

// Best-effort: import Codex-generated by-type files if present.
// Each is optional — we no-op if a type's file hasn't been generated yet.
import { PEOPLE_SCIENTIST } from "./by-type/scientist";
import { PEOPLE_ENGINEER }  from "./by-type/engineer";
import { PEOPLE_MERCHANT }  from "./by-type/merchant";
import { PEOPLE_WRITER }    from "./by-type/writer";
import { PEOPLE_ARTIST }    from "./by-type/artist";
import { PEOPLE_MUSICIAN }  from "./by-type/musician";
import { PEOPLE_GENERAL }   from "./by-type/general";
import { PEOPLE_ADMIRAL }   from "./by-type/admiral";
import { PEOPLE_PROPHET }   from "./by-type/prophet";

function dedupe(list: Person[]): Person[] {
  const seen = new Map<string, Person>();
  for (const p of list) {
    const key = `${p.type}:${p.name.toLowerCase().replace(/\s+/g, "")}`;
    // First entry wins (curated overrides codex output for duplicates).
    if (!seen.has(key)) seen.set(key, p);
  }
  return [...seen.values()].sort((a, b) => (a.born ?? 0) - (b.born ?? 0));
}

export const ALL_PEOPLE: Person[] = dedupe([
  ...CURATED,
  ...PEOPLE_SCIENTIST,
  ...PEOPLE_ENGINEER,
  ...PEOPLE_MERCHANT,
  ...PEOPLE_WRITER,
  ...PEOPLE_ARTIST,
  ...PEOPLE_MUSICIAN,
  ...PEOPLE_GENERAL,
  ...PEOPLE_ADMIRAL,
  ...PEOPLE_PROPHET,
]);
